### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by HUANGJIN169** [jpdigitalman/SimSpirit-Motion-Simulator-Platform#1]
hi hello i love your project can you do a 6 axis pcb design  Thanks

**Comment by jpdigitalman** [comment]
Hi,
Thanks for contacting me. 
Yes. I can do 3 axis, 4 axis, 5 axs, 6 axis, 7 axis, 8 axis, 9 axis, 10, axis, 11, axis and 12 axis version. 

Let's discuss more. 
Thanks. 


    On Monday, 17 July 2023 at 13:02:42 GMT-7, Huang Jin ***@***.***> wrote:  
 
 


hi hello i love your project can you do a 6 axis pcb design Thanks
